// <auto-generated />
using Biblioteca.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20231016031112_beta1")]
    partial class beta1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Biblioteca.Modelos.VariablesLibro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tabla_Libros");
                });

            modelBuilder.Entity("Biblioteca.Modelos.VariablesRegistro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("VariablesLibroID")
                        .HasColumnType("int");

                    b.Property<int>("VariablesUsuariosID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VariablesLibroID");

                    b.HasIndex("VariablesUsuariosID");

                    b.ToTable("Tabla_Registros");
                });

            modelBuilder.Entity("Biblioteca.Modelos.VariablesUsuarios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DUI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teléfono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ID");

                    b.ToTable("Tabla_Usuarios");
                });

            modelBuilder.Entity("Biblioteca.Modelos.VariablesRegistro", b =>
                {
                    b.HasOne("Biblioteca.Modelos.VariablesLibro", "VariablesLibro")
                        .WithMany("CrearRegistro")
                        .HasForeignKey("VariablesLibroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Modelos.VariablesUsuarios", "VariablesUsuarios")
                        .WithMany("CrearRegistro")
                        .HasForeignKey("VariablesUsuariosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VariablesLibro");

                    b.Navigation("VariablesUsuarios");
                });

            modelBuilder.Entity("Biblioteca.Modelos.VariablesLibro", b =>
                {
                    b.Navigation("CrearRegistro");
                });

            modelBuilder.Entity("Biblioteca.Modelos.VariablesUsuarios", b =>
                {
                    b.Navigation("CrearRegistro");
                });
#pragma warning restore 612, 618
        }
    }
}
